# Generated by Django 5.2 on 2025-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_note', models.CharField(max_length=255, verbose_name='ラベル用備考')),
                ('label_issue_count', models.CharField(max_length=100, verbose_name='ラベル発行枚数')),
                ('retest_extension_expiry', models.CharField(max_length=100, verbose_name='リテスト延長使用期限')),
                ('retest_days', models.CharField(max_length=100, verbose_name='リテスト試験日数')),
                ('usage_form', models.CharField(max_length=100, verbose_name='使用剤形')),
                ('expiry_display', models.CharField(max_length=100, verbose_name='使用期限表示')),
                ('guarantee_period', models.CharField(max_length=100, verbose_name='保障期間')),
                ('tolerance_usage', models.CharField(max_length=100, verbose_name='公差使用')),
                ('category', models.CharField(max_length=100, verbose_name='分類')),
                ('unit_price', models.CharField(max_length=100, verbose_name='単価')),
                ('material_id', models.CharField(max_length=100, unique=True, verbose_name='原料ID')),
                ('material_code', models.CharField(max_length=100, verbose_name='原料コード')),
                ('material_category', models.CharField(max_length=100, verbose_name='原料区分')),
                ('material_name', models.CharField(max_length=100, verbose_name='原料名')),
                ('material_sub_code', models.CharField(max_length=100, verbose_name='原料簿コード（サブ）')),
                ('material_main_code', models.CharField(max_length=100, verbose_name='原料簿コード（メイン）')),
                ('origin_country', models.CharField(max_length=100, verbose_name='原産国表示')),
                ('post_test_expiry', models.CharField(max_length=100, verbose_name='受入試験後使用期限')),
                ('qc_note', models.CharField(max_length=255, verbose_name='品質管理備考')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('product_kana', models.CharField(max_length=100, verbose_name='商品名カナ')),
                ('stock_unit_coefficient', models.CharField(max_length=100, verbose_name='在庫単位（係数）')),
                ('change_request', models.CharField(max_length=100, verbose_name='変更申請／変更指示')),
                ('diff_warn_rate', models.CharField(max_length=100, verbose_name='差分警告割合')),
                ('main_bag_weighing', models.CharField(max_length=100, verbose_name='正袋秤量')),
                ('main_bag_weight', models.CharField(max_length=100, verbose_name='正袋重量')),
                ('hq_note', models.CharField(max_length=255, verbose_name='生産本部備考')),
                ('image_path', models.CharField(max_length=255, verbose_name='画像パス')),
                ('order_unit', models.CharField(max_length=100, verbose_name='発注単位')),
                ('packaging', models.CharField(max_length=100, verbose_name='荷姿')),
                ('correction_info', models.CharField(max_length=100, verbose_name='補正情報')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='製造所')),
                ('standard', models.CharField(max_length=100, verbose_name='規格')),
                ('procurement_type', models.CharField(max_length=100, verbose_name='調達区分')),
                ('supplier', models.CharField(max_length=100, verbose_name='販売者')),
                ('tare_weight', models.CharField(max_length=100, verbose_name='風袋重量')),
                ('unnamed_36', models.CharField(max_length=100, verbose_name='Unnamed: 36')),
                ('unnamed_37', models.CharField(max_length=100, verbose_name='Unnamed: 37')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
