# Generated by Django 5.2 on 2025-05-28 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=50, unique=True, verbose_name='原料ID')),
                ('material_name', models.CharField(max_length=200, verbose_name='原料名')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='単価')),
                ('material_category', models.CharField(blank=True, max_length=100, verbose_name='原料区分')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供給元')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '原料',
                'verbose_name_plural': '原料',
                'ordering': ['material_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='製品ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='製品名')),
                ('factory', models.CharField(max_length=100, verbose_name='工場')),
                ('sales_destination', models.CharField(blank=True, max_length=200, verbose_name='販売先')),
                ('filling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='充填価格')),
                ('batch_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='仕込量')),
                ('output_amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='出来数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.IntegerField(verbose_name='パターン')),
                ('blend_amount_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='配合量(kg)')),
                ('correction_category', models.CharField(blank=True, max_length=50, verbose_name='補正区分')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='原料')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.product', verbose_name='製品')),
            ],
            options={
                'verbose_name': '配合詳細',
                'verbose_name_plural': '配合詳細',
                'unique_together': {('product', 'material', 'pattern')},
            },
        ),
    ]
