from django.db import models

class Material(models.Model):
    label_note = models.CharField('ラベル用備考', max_length=255, blank=True, null=True)
    label_issue_count = models.CharField('ラベル発行枚数', max_length=100, blank=True, null=True)
    retest_extension_expiry = models.CharField('リテスト延長使用期限', max_length=100, blank=True, null=True)
    retest_days = models.CharField('リテスト試験日数', max_length=100, blank=True, null=True)
    usage_form = models.CharField('使用剤形', max_length=100, blank=True, null=True)
    expiry_display = models.CharField('使用期限表示', max_length=100, blank=True, null=True)
    guarantee_period = models.CharField('保障期間', max_length=100, blank=True, null=True)
    tolerance_usage = models.CharField('公差使用', max_length=100, blank=True, null=True)
    category = models.CharField('分類', max_length=100, blank=True, null=True)
    unit_price = models.CharField('単価', max_length=100, blank=True, null=True)
    material_id = models.CharField('原料ID', max_length=100, unique=True)
    material_code = models.CharField('原料コード', max_length=100, blank=True, null=True)
    material_category = models.CharField('原料区分', max_length=100, blank=True, null=True)
    material_name = models.CharField('原料名', max_length=100, blank=True, null=True)
    material_sub_code = models.CharField('原料簿コード（サブ）', max_length=100, blank=True, null=True)
    material_main_code = models.CharField('原料簿コード（メイン）', max_length=100, blank=True, null=True)
    origin_country = models.CharField('原産国表示', max_length=100, blank=True, null=True)
    post_test_expiry = models.CharField('受入試験後使用期限', max_length=100, blank=True, null=True)
    qc_note = models.CharField('品質管理備考', max_length=255, blank=True, null=True)
    product_name = models.CharField('商品名', max_length=100, blank=True, null=True)
    product_kana = models.CharField('商品名カナ', max_length=100, blank=True, null=True)
    stock_unit_coefficient = models.CharField('在庫単位（係数）', max_length=100, blank=True, null=True)
    change_request = models.CharField('変更申請／変更指示', max_length=100, blank=True, null=True)
    diff_warn_rate = models.CharField('差分警告割合', max_length=100, blank=True, null=True)
    main_bag_weighing = models.CharField('正袋秤量', max_length=100, blank=True, null=True)
    main_bag_weight = models.CharField('正袋重量', max_length=100, blank=True, null=True)
    hq_note = models.CharField('生産本部備考', max_length=255, blank=True, null=True)
    image_path = models.CharField('画像パス', max_length=255, blank=True, null=True)
    order_unit = models.CharField('発注単位', max_length=100, blank=True, null=True)
    packaging = models.CharField('荷姿', max_length=100, blank=True, null=True)
    correction_info = models.CharField('補正情報', max_length=100, blank=True, null=True)
    manufacturer = models.CharField('製造所', max_length=100, blank=True, null=True)
    standard = models.CharField('規格', max_length=100, blank=True, null=True)
    procurement_type = models.CharField('調達区分', max_length=100, blank=True, null=True)
    supplier = models.CharField('販売者', max_length=100, blank=True, null=True)
    tare_weight = models.CharField('風袋重量', max_length=100, blank=True, null=True)
    unnamed_36 = models.CharField('Unnamed: 36', max_length=100, blank=True, null=True)
    unnamed_37 = models.CharField('Unnamed: 37', max_length=100, blank=True, null=True)

    is_active = models.BooleanField('有効', default=True)
    created_at = models.DateTimeField('作成日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時', auto_now=True)

    def __str__(self):
        return self.material_name or self.material_id
